# Generated by Django 6.0.5 on 2026-06-10 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('conteudo', models.TextField()),
                ('humor', models.CharField(blank=True, choices=[('muito_triste', 'Muito Triste'), ('triste', 'Triste'), ('neutro', 'Neutro'), ('feliz', 'Feliz'), ('muito_feliz', 'Muito Feliz')], max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='entradas_diario', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
                'db_table': 'diario',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['paciente'], name='idx_diario_paciente')],
            },
        ),
    ]
