# Generated by Django 6.0.5 on 2026-06-09 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='paciente', to='contas.usuario')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='PreferenciasPrivacidade',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('compartilhar_diario', models.BooleanField(blank=True, null=True)),
                ('compartilhar_autotestes', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(blank=True, db_column='paciente_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_privacidade', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Preferências de Privacidade',
                'verbose_name_plural': 'Preferências de Privacidade',
                'db_table': 'preferencias_privacidade',
            },
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('especialidade', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='terapeuta', to='contas.usuario')),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
                'db_table': 'terapeuta',
            },
        ),
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('aceito', models.BooleanField(default=False)),
                ('data_aceita', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to='usuarios.paciente')),
                ('terapeuta', models.ForeignKey(db_column='terapeuta_id', on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to='usuarios.terapeuta')),
            ],
            options={
                'verbose_name': 'Consentimento',
                'verbose_name_plural': 'Consentimentos',
                'db_table': 'consentimento',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recusado', 'Recusado'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='pendente', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_encerramento', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='vinculos', to='usuarios.paciente')),
                ('terapeuta', models.ForeignKey(db_column='terapeuta_id', on_delete=django.db.models.deletion.RESTRICT, related_name='vinculos', to='usuarios.terapeuta')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'db_table': 'vinculo',
            },
        ),
    ]
