# Generated by Django 6.0.5 on 2026-06-10 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoteste',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoteste',
                'verbose_name_plural': 'Autotestes',
                'db_table': 'autoteste',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoTeste',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('classificacao', models.CharField(choices=[('a fazer', 'a fazer'), ('em andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='a fazer', max_length=20)),
                ('data_realizada', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='aplicacoes_teste', to='usuarios.paciente')),
                ('autoteste', models.ForeignKey(db_column='auto_teste_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='aplicacoes', to='testes.autoteste')),
            ],
            options={
                'verbose_name': 'Aplicação de Teste',
                'verbose_name_plural': 'Aplicações de Teste',
                'db_table': 'aplicacao_teste',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('ordem_exibicao', models.IntegerField(blank=True, null=True)),
                ('autoteste', models.ForeignKey(db_column='autoteste_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='questoes', to='testes.autoteste')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'db_table': 'questao',
                'ordering': ['ordem_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('valor_resposta', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aplicacao_teste', models.ForeignKey(db_column='aplicacao_teste_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='respostas', to='testes.aplicacaoteste')),
                ('questao', models.ForeignKey(db_column='questao_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='respostas', to='testes.questao')),
            ],
            options={
                'verbose_name': 'Resposta de Questão',
                'verbose_name_plural': 'Respostas de Questões',
                'db_table': 'resposta_questao',
            },
        ),
        migrations.AddConstraint(
            model_name='questao',
            constraint=models.UniqueConstraint(fields=('autoteste', 'ordem_exibicao'), name='uq_questao_autoteste_ordem'),
        ),
        migrations.AddIndex(
            model_name='respostaquestao',
            index=models.Index(fields=['questao'], name='idx_resposta_questao'),
        ),
    ]
